server:
  port: 9090
#  ssl:
#    enabled: true
#    key-store=classpath: keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12

JWT_SECRET: specify-your-secret-key-is-here-36chars

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_details
    username: dhruv
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: ${SECURITY_USERNAME:admin}
      password: ${SECURITY_PASSWORD:admin123}

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  #  hibernate:
  #    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here}
  access-token-expiry-minutes: 15
  refresh-token-expiry-days: 30